name: Static Site
on:
  push:
    branches:
      - main
    
permissions:
  contents: read
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    # configure gcloud 'setup-gcloud' automatically
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/307385049786/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'my-service1@static-website-420015.iam.gserviceaccount.com'
