-uses: 'google-github-actions/auth@v2'
 with:
    service_account: '...' # my-service1@static-website-420015.iam.gserviceaccount.com
    workload_identity_provider: '...' # "projects/123456789/locations/global/workloadIdentityPools/github/providers/my-repo"
