name: WorkflowName
on:
  push:
    branches:
      - main
jobs:
  job_id:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: 'actions/checkout@v4'
    - uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/307385049786/locations/global/workloadIdentityPools/github/providers/my-repo'
        service_account: 'my-service1@static-website-420015.iam.gserviceaccount.com'
